apiVersion: v1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: murali383/hello-service
        ports:
        - containerPort: 8080