apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    app: hello-label
spec:
  containers:
  - name: hello-container
    image: nginx
  - name: shell
    image: centos:7
    command:
      - "bin/bash"
      - "-c"
      - "sleep 10000"